services:
  postgresql:
    image: 'postgres:18.1-bookworm'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'

  meilisearch:
    image: getmeilisearch/meilisearch:v1.31 # 최신 버전 권장
    container_name: meili-engine
    ports:
      - "7700:7700" # 기본 포트
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_MAX_INDEXING_MEMORY=128Mb

    #    volumes:
    #      - ./meili_data:/meili_data
    #    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
